coverage:
  status:
    project:
      default:
        target: auto      # pass as long as coverage doesn't drop vs baseline
        threshold: 1%     # allow up to 1% drop before failing
    patch:
      default:
        target: auto
        threshold: 1%
